import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { AuthenticationProvider } from "@/context/AuthContext";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <AuthenticationProvider>
                <body className={inter.className}>
                    <main>{children}</main>
                    <Toaster />
                </body>
            </AuthenticationProvider>
        </html>
    );
}
