name: Vercel Production Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BE_PROJECT_ID }}
on:
    push:
        branches:
            - main
jobs:
    Test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        strategy:
            matrix:
                node-version: [20.x]
                architecture: [x64]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v2

            - name: Install Dependencies
              run: npm i

            - name: Run Tests
              run: npx jest

    Deploy-Production:
        needs: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
